emploi/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from iscae_emploi import  views
from django.conf.urls import  handler500,handler404

admin.site.site_title ="ISCAE G-EMPLOI administration"
admin.site.index_title ="ISCAE G-EMPLOI"
admin.site.site_header = "ISCAE"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('user.urls',namespace='user') ),

    path('iscae_emploi/', include('iscae_emploi.urls',namespace='iscae_emploi')),




] + static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)



handler404 = views.handler404
handler500 = views.handler500

iscae_emploi/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView,LogoutView
app_name='iscae_emploi'

urlpatterns = [
    path('login/',LoginView.as_view(template_name='user/login.html') , name='login'),
    path('logout/',LogoutView.as_view() , name='logout'),



    path('index/',views.index , name='index'),
    path('config/',views.config , name='config'),
    path('dp/',views.departement , name='dp'),
    path('Cours/',views.cours , name='cours'),
    path('salles/',views.salle , name='salle'),
    path('niveaux/',views.niveau , name='niveau'),
    path('jours/',views.jours , name='jours'),
    path('creneaux/',views.creneaux , name='creneaux'),
    path('calandriers/',views.calandriers , name='calandriers'),
    path('seances/<int:pk>/',views.seance , name='seances'),
    path('chevauch/<int:pk>/',views.chevauch , name='chevauch'),


    path('seance_download/',views.seance_download , name='seance_download'),
    path('emploi_download/',views.emploi_download , name='emploi_download'),


    #************* add object **************

    path('dep_ajout/',views.dep_ajout , name='dep_ajout'),
    path('dep_edit/<int:pk>/',views.dep_edit , name='dep_edit'),
    path('dep_delete/<int:pk>/',views.dep_delete , name='dep_delete'),

    path('creneau_ajout/',views.creneau_ajout , name='creneau_ajout'),
    path('creneau_edit/<int:pk>/',views.creneau_edit , name='creneau_edit'),
    path('creneau_delete/<int:pk>/',views.creneau_delete , name='creneau_delete'),

    path('cal_ajout/',views.calandrier_ajout , name='cal_ajout'),
    path('cal_edit/<int:pk>/',views.calandrier_edit , name='cal_edit'),
    path('cal_delete/<int:pk>/',views.calandrier_delete , name='cal_delete'),

    path('sall_ajout/',views.sall_ajout , name='sall_ajout'),
    path('sall_edit/<int:pk>/',views.sall_edit , name='sall_edit'),
    path('sall_delete/<int:pk>/',views.sall_delete , name='sall_delete'),

    path('seance_ajout/<int:pk>/',views.seance_ajout , name='seance_ajout'),
    path('seance_edit/<int:pk>/',views.seance_edit , name='seance_edit'),
    path('seance_delete/<int:pk>/',views.seance_delete , name='seance_delete'),

    path('matier_ajout/<int:pk>/',views.matier_ajout , name='matier_ajout'),
    path('matier_edit/<int:pk>/',views.matier_edit , name='matier_edit'),
    path('matier_delete/<int:pk>/',views.matier_delete , name='matier_delete'),

    path('prof_ajout/<int:pk>/',views.prof_ajout , name='prof_ajout'),
    path('prof_edit/<int:pk>/',views.prof_edit , name='prof_edit'),
    path('prof_delete/<int:pk>/',views.prof_delete , name='prof_delete'),

    path('filier_ajout/<int:pk>/',views.filier_ajout , name='filier_ajout'),
    path('filier_edit/<int:pk>/',views.filier_edit , name='filier_edit'),
    path('filier_delete/<int:pk>/',views.filier_delete , name='filier_delete'),

    path('classe_ajout/<int:pk>/',views.classe_ajout , name='classe_ajout'),
    path('classe_edit/<int:pk>/',views.classe_edit , name='classe_edit'),
    path('classe_delete/<int:pk>/',views.classe_delete , name='classe_delete'),

    path('joure_ajout/',views.joure_ajout , name='joure_ajout'),
    path('joure_edit/<int:pk>/',views.joure_edit , name='joure_edit'),
    path('joure_delete/<int:pk>/',views.joure_delete , name='joure_delete'),

    path('niveau_ajout/',views.niveau_ajout , name='niveau_ajout'),
    path('niveau_edit/<int:pk>/',views.niveau_edit , name='niveau_edit'),
    path('niveau_delete/<int:pk>/',views.niveau_delete , name='niveau_delete'),

    path('cours_ajout/<int:pk>/',views.cours_ajout , name='cours_ajout'),
    path('cours_edit/<int:pk>/',views.cours_edit , name='cours_edit'),
    path('cours_delete/<int:pk>/',views.cours_delete , name='cours_delete'),

    path('groupe_ajout/<int:pk>/',views.groupe_ajout , name='groupe_ajout'),
    path('groupe_edit/<int:pk>/',views.groupe_edit , name='groupe_edit'),
    path('groupe_delete/<int:pk>/',views.groupe_delete , name='groupe_delete'),

    path('detail_c_ajout/<int:pk>/',views.detail_c_ajout , name='detail_c_ajout'),
    path('detail_c_edit/<int:pk>/',views.detail_c_edit , name='detail_c_edit'),
    path('detail_c_delete/<int:pk>/',views.detail_c_delete , name='detail_c_delete'),

    path('prof_indispo_ajout/<int:pk>/',views.prof_indispo_ajout , name='prof_indispo_ajout'),
    path('prof_indispo_edit/<int:pk>/',views.prof_indispo_edit , name='prof_indispo_edit'),
    path('prof_indispo_delete/<int:pk>/',views.prof_indispo_delete , name='prof_indispo_delete'),

    path('prof_preferance_ajout/<int:pk>/',views.prof_preferance_ajout , name='prof_preferance_ajout'),
    path('prof_preferance_edit/<int:pk>/',views.prof_preferance_edit , name='prof_preferance_edit'),
    path('prof_preferance_delete/<int:pk>/',views.prof_preferance_delete , name='prof_preferance_delete'),

    path('groupe_indispo_ajout/<int:pk>/',views.groupe_indispo_ajout , name='groupe_indispo_ajout'),
    path('groupe_indispo_edit/<int:pk>/',views.groupe_indispo_edit , name='groupe_indispo_edit'),
    path('groupe_indispo_delete/<int:pk>/',views.groupe_indispo_delete , name='groupe_indispo_delete'),

    path('cal_exception_ajout/<int:pk>/',views.cal_exception_ajout , name='cal_exception_ajout'),
    path('cal_exception_edit/<int:pk>/',views.cal_exception_edit , name='cal_exception_edit'),
    path('cal_exception_delete/<int:pk>/',views.cal_exception_delete , name='cal_exception_delete'),

    path('chevauch_ajout/<int:pk>/',views.chevauch_ajout , name='chevauch_ajout'),
    path('chevauch_edit/<int:pk>/',views.chevauch_edit , name='chevauch_edit'),
    path('chevauch_delete/<int:pk>/',views.chevauch_delete , name='chevauch_delete'),



    # ##############end add object  ###############

    path('dep_matiers/<int:pk>/',views.dep_matiers , name='dep_matiers'),
    path('filier_classes/<int:pk>/',views.filier_classes , name='filier_classes'),
    path('classe_groupe/<int:pk>/',views.classe_groupe , name='classe_groupe'),
    path('classe_matiere/<int:pk>/',views.classe_matiere , name='classe_matiere'),

    path('groupe_cours/<int:pk>/',views.groupe_cours , name='groupe_cours'),
    path('groupe_indispo/<int:pk>/',views.groupe_indispo , name='groupe_indispo'),
    path('groupe_indispo_creneau/<int:pk>/',views.groupe_indispo_creneau , name='groupe_indispo_creneau'),
    path('groupe_indispo_jours/<int:pk>/',views.groupe_indispo_jours , name='groupe_indispo_jours'),
    path('prof_cours/<int:pk>/',views.prof_cours , name='prof_cours'),
    path('prof_indispo/<int:pk>/',views.prof_indispo , name='prof_indispo'),
    path('prof_indispo_creneau/<int:pk>/',views.prof_indispo_creneau , name='prof_indispo_creneau'),
    path('prof_indispo_jours/<int:pk>/',views.prof_indispo_jours , name='prof_indispo_jours'),
    path('prof_preferance/<int:pk>/',views.prof_preferance , name='prof_preferance'),
    path('detail_c/<int:pk>/',views.detail_c , name='detail_c'),
    path('filiere/<int:pk>/',views.filiere , name='filiere'),
    path('prof/<int:pk>/',views.prof , name='prof'),
    path('j_creneaux/<int:pk>/',views.j_creneaux , name='j_creneaux'),
    path('c_exception/<int:pk>/',views.c_exception , name='c_exception'),


    path('emploi/<int:pk>/',views.emploi , name='emploi'),


]

user/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView, LogoutView
from django.conf.urls.static import static
from django.conf import settings
app_name='user'

urlpatterns = [

    # path('login/', LoginView.as_view(template_name='user/login.html'), name='login'),
    path('', views.login_user, name=''),
    # path('logout/', LogoutView.as_view(template_name='user/logout.html'), name='logout'),
    path('logout/', views.logout_user, name='logout')
    ,]

iscae_emploi/forms.py
from django import forms
from django.forms import DateInput

from .models import *


class DepartementForm(forms.ModelForm):

    class Meta:
        model = Departement
        fields = '__all__'


class SalleForm(forms.ModelForm):

    class Meta:
        model = Salle
        fields = '__all__'


class MatierForm(forms.ModelForm):

    class Meta:
        model = Matier
        fields = ['nom']


class ProfesseurForm(forms.ModelForm):

    class Meta:
        model = Professeur
        fields = ['nom','prenom','email','specialite','mobile']


class FilierForm(forms.ModelForm):

    class Meta:
        model = Filier
        fields = ['nom']


class ClasseForm(forms.ModelForm):

    class Meta:
        model = Classe
        fields = ['nom','niveau']


class JourForm(forms.ModelForm):

    class Meta:
        model = Jour
        fields = '__all__'


class CoursForm(forms.ModelForm):

    class Meta:
        model = Cours
        fields = ['nom','type','prof','matier','salle','charge']


class GroupeForm(forms.ModelForm):

    class Meta:
        model = Groupe
        fields = ['nom','nombre_etudiant']


class CreneauForm(forms.ModelForm):

    class Meta:
        model = Creneau
        fields = '__all__'

class DetailcalandrierForm(forms.ModelForm):

    class Meta:
        model = DetailCalandrier
        fields = ['jour','créneaux']

class ExceptioncalandrierForm(forms.ModelForm):

    class Meta:
        model = ExceptionCalandrier
        fields = ['nom','créneau','type']

class SeanceForm(forms.ModelForm):

    class Meta:
        model = Seance
        fields = ['cours','créneau']
        
        

class PreferanceprofForm(forms.ModelForm):

    class Meta:
        model = Preferance_prof
        fields = ['jour','créneaux']


class GroupeChevauchementForm(forms.ModelForm):

    class Meta:
        model = GroupeChevauchement
        fields = ['groupe1','groupe2']
        
    
    def __init__(self, pk, *args, **kwargs):
        super(GroupeChevauchementForm, self).__init__(*args, **kwargs)
        self.fields['groupe1'].queryset = Groupe.objects.filter(classe_id=pk)
        self.fields['groupe2'].queryset = Groupe.objects.filter(classe_id=pk)


class NiveauForm(forms.ModelForm):

    class Meta:
        model = Niveau
        fields ='__all__'

class IndispoprofForm(forms.ModelForm):

    class Meta:
        model = IndispoProf
        fields = ['jours','créneaux']
        date_debut = forms.DateTimeField(
        input_formats=['%d/%m/%Y %H:%M'],
        widget=forms.DateTimeInput(attrs={
            'class': 'form-control datetimepicker-input',
            'data-target': '#datetimepicker1'
        }))
        date_fin = forms.DateTimeField(
            input_formats=['%d/%m/%Y %H:%M'],
            widget=forms.DateTimeInput(attrs={
                'class': 'form-control datetimepicker-input',
                'data-target': '#datetimepicker2'
            }))

class IndispogroupeForm(forms.ModelForm):


    class Meta:
        model = IndispoGroupe
        fields = ['jours','créneaux']
        date_debut = forms.DateTimeField(
        input_formats=['%d/%m/%Y %H:%M'],
        widget=forms.DateTimeInput(attrs={
            'class': 'form-control datetimepicker-input',
            'data-target': '#datetimepicker1'
        }))
        date_fin = forms.DateTimeField(
            input_formats=['%d/%m/%Y %H:%M'],
            widget=forms.DateTimeInput(attrs={
                'class': 'form-control datetimepicker-input',
                'data-target': '#datetimepicker2'
            }))



class CalandrierForm(forms.ModelForm):

    class Meta:
        model = CalandrierStandard
        fields = '__all__'

iscae_emploi/templates/creneau_delete.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}

{% block body %}

<div class="all-content-wrapper" style="margin-top:80px">
<div class="single-pro-review-area mt-t-30 mg-b-15">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                        <div class="product-payment-inner-st">
                            <ul id="myTabedu1" class="tab-review-design">
                                <li class="active"><a href="#description">Suppression du Créneau</a></li>
                            </ul>
                            <div id="myTabContent" class="tab-content custom-product-edit">
                                <div class="product-tab-list tab-pane fade active in" id="description">
                                    <div class="row">
                                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                            <div class="review-content-section">
                                            <form action="{% url 'iscae_emploi:creneau_delete' item.id%}" method="POST">
                                                {% csrf_token %}
                                                <p>confirmer la suppression du Créneau "{{item}}"</p>
                                                <input class="btn btn-warning mt-4" onClick="javascript:history.go(-1);" type="button" value="Annuler">>
                                                <input class="btn btn-danger mt-4" type="submit" value="Confirmer">
                                            </form>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
</div>
</div>




{% endblock %}

iscae_emploi/templates/detail_c.html
{% extends 'base.html' %}
{% load static %}

{% block body %}

<body>
    <!-- Start Welcome area -->
    <div class="all-content-wrapper">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="logo-pro">
                        <a href="index.html"><img class="main-logo" src="img/logo/logo.png" alt="" /></a>
                    </div>
                </div>
            </div>
        </div>

        <div class="product-status mg-b-15">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                        <div class="product-status-wrap drp-lst">
                            <h3>Calandrier {{cal.nom}}</h3>
                            <h4>Detail</h4>
                            <div class="add-product">
                                <a href="{% url 'iscae_emploi:detail_c_ajout' cal.id %}">
                                    <i class="fa fa-plus" aria-hidden="true"></i></a>
                            </div>
                            <div class="asset-inner">
                                <table>
                                    <tr>
                                        <th>Jour</th>
                                        <th>Créneau</th>
                                        <th>Action</th>
                                    </tr>
                                    {% for d in detail %}
                                    <tr>
                                        <td>{{d.jour}}</td>
                                        <td>
                                           <button type="button" class="btn btn-custon-rounded-three btn-default">
                                               <a href="{% url 'iscae_emploi:j_creneaux' d.jour.id %}"><i class="fa fa-hourglass-half" ></i>  Créneaux</a></button>
                                        </td>

                                        <td>
                                             <button type="button" class="btn btn-custon-three btn-primary">
                                                <a href="{% url 'iscae_emploi:detail_c_edit' d.id %}" style="color:white;"><i class="fa fa-edit" ></i></a>
                                            </button>


                                            <button type="button" class="btn btn-custon-three btn-danger">
                                                <a  href="{% url 'iscae_emploi:detail_c_delete' d.id %}" style="color:white;"><i class="fa fa-trash-alt" ></i></a>
                                            </button>
                                        </td>

                                    </tr>
                                    {% endfor %}
                                </table>
                            </div>
                            <div class="custom-pagination">
                                <nav aria-label="Page navigation example">
                                    <form method="get">
                                    <ul class="pagination">

                                        {% for i in pagination.page_range %}

                                        <li class="page-item {% if i == page_number %} active {% endif %}">
                                            <a class="page-link" href="?page={{ i }}">{{i}}</a>
                                        </li>

                                        {% endfor %}
                                    </ul>
                                        </form>
                                </nav>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>


</body>

{% endblock body %}

iscae_emploi/templates/index.html
{% extends 'base.html' %}
{% load static %}


{% block body %}

<body>
    <!-- Start Welcome area -->
    <div class="all-content-wrapper">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="logo-pro">
                        <a href="index.html"><img class="main-logo" src="img/logo/logo.png" alt="" /></a>
                    </div>
                </div>
            </div>
        </div>

        <div class="product-status mg-b-15">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                        <div class="product-status-wrap drp-lst">
                            <h3><i class="fa fa-building" aria-hidden="true"></i>  Departements </h3>
                            <h4>Listes des Departements</h4>
                            <div class="add-product">
                                <a href="{% url 'iscae_emploi:dep_ajout' %}">
                                    <i class="fa fa-plus" aria-hidden="true"></i>
                                </a>
                            </div>
                            <div class="asset-inner">
                                <table>
                                    <tr>
                                        <th>Nom</th>
                                        <th>Responsable</th>
                                        <th>Email</th>
                                        <th>Tel</th>

                                        <th>Action</th>
                                    </tr>
                                    {% for dp in departements %}
                                    <tr>
                                        <td>{{dp.nom}}</td>
                                        <td>{{dp.chef}}</td>
                                        <td>{{dp.email}}</td>
                                        <td>{{dp.mobile}}</td>
                                        <td>

                                           <button type="button" class="btn btn-custon-rounded-three btn-default">
                                               <a href="{% url 'iscae_emploi:filiere' dp.id %}"><i class="fa fa-university"></i>  Filiéres</a></button>

                                           <button type="button" class="btn btn-custon-rounded-three btn-default">
                                               <a href="{% url 'iscae_emploi:prof' dp.id %}"><i class="fa fa-user-tie"></i>  Professeurs</a></button>


                                            <button type="button" class="btn btn-custon-rounded-three btn-default">
                                                <a href="{% url 'iscae_emploi:dep_matiers' dp.id %}"><i class="fa fa-book"></i>  Matiére</a></button>

                                            <button type="button" class="btn btn-custon-three btn-primary">
                                                <a href="{% url 'iscae_emploi:dep_edit' dp.id %}" style="color:white;"><i class="fa fa-edit" aria-hidden="true"></i></a></button>


                                          <button type="button" class="btn btn-custon-three btn-danger">
                                                <a  href="{% url 'iscae_emploi:dep_delete' dp.id %}" style="color:white;"><i class="fa fa-trash-alt" aria-hidden="true"></i></a>
                                          </button>

                                        </td>
                                    </tr>
                                    {% endfor %}
                                </table>
                            </div>
                            <div class="custom-pagination">
                                <nav aria-label="Page navigation example">
                                     <form method="get">
                                    <ul class="pagination">

                                        {% for i in pagination.page_range %}

                                        <li class="page-item {% if i == page_number %} active {% endif %}">
                                            <a class="page-link" href="?page={{ i }}">{{i}}</a>
                                        </li>

                                        {% endfor %}
                                    </ul>
                                        </form>
                                </nav>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>


</body>

{% endblock body %}

iscae_emploi/templates/joure_delete.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}

{% block body %}

<div class="all-content-wrapper" style="margin-top:80px">
<div class="single-pro-review-area mt-t-30 mg-b-15">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                        <div class="product-payment-inner-st">
                            <ul id="myTabedu1" class="tab-review-design">
                                <li class="active"><a href="#description">Suppression de Jour</a></li>
                            </ul>
                            <div id="myTabContent" class="tab-content custom-product-edit">
                                <div class="product-tab-list tab-pane fade active in" id="description">
                                    <div class="row">
                                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                            <div class="review-content-section">
                                            <form action="{% url 'iscae_emploi:joure_delete' item.id%}" method="POST">
                                                {% csrf_token %}
                                                <p>confirmer la suppression du jour "{{item}}"</p>
                                                <input class="btn btn-warning mt-4" onClick="javascript:history.go(-1);" type="button" value="Annuler">
                                                <input class="btn btn-danger mt-4" type="submit" value="Confirmer">
                                            </form>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
</div>
</div>




{% endblock %}

iscae_emploi/templates/niveau_delete.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}

{% block body %}

<div class="all-content-wrapper" style="margin-top:80px">
<div class="single-pro-review-area mt-t-30 mg-b-15">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                        <div class="product-payment-inner-st">
                            <ul id="myTabedu1" class="tab-review-design">
                                <li class="active"><a href="#description">Suppression du Niveau</a></li>
                            </ul>
                            <div id="myTabContent" class="tab-content custom-product-edit">
                                <div class="product-tab-list tab-pane fade active in" id="description">
                                    <div class="row">
                                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                            <div class="review-content-section">
                                            <form action="{% url 'iscae_emploi:niveau_delete' item.id%}" method="POST">
                                                {% csrf_token %}
                                                <p>confirmer la suppression du Niveau "{{item}}"</p>
                                                 <input class="btn btn-warning mt-4" onClick="javascript:history.go(-1);" type="button" value="Annuler">
                                                <input class="btn btn-danger mt-4" type="submit" value="Confirmer">
                                            </form>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
</div>
</div>




{% endblock %}

iscae_emploi/templates/prof_indispo.html
{% extends 'base.html' %}
{% load static %}

{% block body %}

<body>
    <!-- Start Welcome area -->
    <div class="all-content-wrapper">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="logo-pro">
                        <a href="index.html"><img class="main-logo" src="img/logo/logo.png" alt="" /></a>
                    </div>
                </div>
            </div>
        </div>

        <div class="product-status mg-b-15">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                        <div class="product-status-wrap drp-lst">
                            <h4>L'indisponibilité du Professeur {{prof.nom}}</h4>
                            <div class="add-product">
                                <a href="{% url 'iscae_emploi:prof_indispo_ajout' prof.id%}">
                                    <i class="fa fa-plus" aria-hidden="true"></i>
                                </a>
                            </div>
                            <div class="asset-inner">
                                <table>
                                    <tr>
                                        <th>Date debut</th>
                                        <th>Date fin</th>

                                        <th>Action</th>
                                    </tr>
                                    {% for g in p_indispo %}
                                    <tr>
                                        <td>{{g.date_debut}}</td>
                                        <td>{{g.date_fin}}</td>


                                        <td>
                                            <button type="button" class="btn btn-custon-rounded-three btn-default">
                                                <a href="{% url 'iscae_emploi:prof_indispo_jours' g.id %}" ><i class="fab fa-dashcube" ></i> Jours</a>
                                           </button>
                                            <button type="button" class="btn btn-custon-rounded-three btn-default">
                                                <a href="{% url 'iscae_emploi:prof_indispo_creneau' g.id %}" ><i class="fa fa-hourglass-half" ></i> Créneaux</a>
                                           </button>
                                           <button type="button" class="btn btn-custon-three btn-primary">
                                                <a href="{% url 'iscae_emploi:prof_indispo_edit' g.id %}" style="color:white;"><i class="fa fa-edit" ></i></a>
                                           </button>


                                            <button type="button" class="btn btn-custon-three btn-danger">
                                                <a  href="{% url 'iscae_emploi:prof_indispo_delete' g.id %}" style="color:white;"><i class="fa fa-trash-alt" ></i></a>
                                            </button>
                                        </td>
                                    </tr>
                                    {% endfor %}
                                </table>
                            </div>
                            <div class="custom-pagination">
                                <nav aria-label="Page navigation example">
                                     <form method="get">
                                    <ul class="pagination">
                                        {% for i in pagination.page_range %}

                                        <li class="page-item {% if i == page_number %} active {% endif %}">
                                            <a class="page-link" href="?page={{ i }}">{{i}}</a>
                                        </li>

                                        {% endfor %}
                                    </ul>
                                        </form>
                                </nav>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>


</body>

{% endblock body %}