emploi/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from iscae_emploi import  views
from django.conf.urls import  handler500,handler404

admin.site.site_title ="ISCAE G-EMPLOI administration"
admin.site.index_title ="ISCAE G-EMPLOI"
admin.site.site_header = "ISCAE"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('user.urls',namespace='user') ),

    path('iscae_emploi/', include('iscae_emploi.urls',namespace='iscae_emploi')),




] + static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)



handler404 = views.handler404
handler500 = views.handler500

iscae_emploi/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView,LogoutView
app_name='iscae_emploi'

urlpatterns = [
    path('login/',LoginView.as_view(template_name='user/login.html') , name='login'),
    path('logout/',LogoutView.as_view() , name='logout'),



    path('index/',views.index , name='index'),
    path('config/',views.config , name='config'),
    path('dp/',views.departement , name='dp'),
    path('Cours/',views.cours , name='cours'),
    path('salles/',views.salle , name='salle'),
    path('niveaux/',views.niveau , name='niveau'),
    path('jours/',views.jours , name='jours'),
    path('creneaux/',views.creneaux , name='creneaux'),
    path('calandriers/',views.calandriers , name='calandriers'),
    path('seances/<int:pk>/',views.seance , name='seances'),
    path('chevauch/<int:pk>/',views.chevauch , name='chevauch'),


    path('seance_download/',views.seance_download , name='seance_download'),
    path('emploi_download/',views.emploi_download , name='emploi_download'),


    #************* add object **************

    path('dep_ajout/',views.dep_ajout , name='dep_ajout'),
    path('dep_edit/<int:pk>/',views.dep_edit , name='dep_edit'),
    path('dep_delete/<int:pk>/',views.dep_delete , name='dep_delete'),

    path('creneau_ajout/',views.creneau_ajout , name='creneau_ajout'),
    path('creneau_edit/<int:pk>/',views.creneau_edit , name='creneau_edit'),
    path('creneau_delete/<int:pk>/',views.creneau_delete , name='creneau_delete'),

    path('cal_ajout/',views.calandrier_ajout , name='cal_ajout'),
    path('cal_edit/<int:pk>/',views.calandrier_edit , name='cal_edit'),
    path('cal_delete/<int:pk>/',views.calandrier_delete , name='cal_delete'),

    path('sall_ajout/',views.sall_ajout , name='sall_ajout'),
    path('sall_edit/<int:pk>/',views.sall_edit , name='sall_edit'),
    path('sall_delete/<int:pk>/',views.sall_delete , name='sall_delete'),

    path('seance_ajout/<int:pk>/',views.seance_ajout , name='seance_ajout'),
    path('seance_edit/<int:pk>/',views.seance_edit , name='seance_edit'),
    path('seance_delete/<int:pk>/',views.seance_delete , name='seance_delete'),

    path('matier_ajout/<int:pk>/',views.matier_ajout , name='matier_ajout'),
    path('matier_edit/<int:pk>/',views.matier_edit , name='matier_edit'),
    path('matier_delete/<int:pk>/',views.matier_delete , name='matier_delete'),

    path('prof_ajout/<int:pk>/',views.prof_ajout , name='prof_ajout'),
    path('prof_edit/<int:pk>/',views.prof_edit , name='prof_edit'),
    path('prof_delete/<int:pk>/',views.prof_delete , name='prof_delete'),

    path('filier_ajout/<int:pk>/',views.filier_ajout , name='filier_ajout'),
    path('filier_edit/<int:pk>/',views.filier_edit , name='filier_edit'),
    path('filier_delete/<int:pk>/',views.filier_delete , name='filier_delete'),

    path('classe_ajout/<int:pk>/',views.classe_ajout , name='classe_ajout'),
    path('classe_edit/<int:pk>/',views.classe_edit , name='classe_edit'),
    path('classe_delete/<int:pk>/',views.classe_delete , name='classe_delete'),

    path('joure_ajout/',views.joure_ajout , name='joure_ajout'),
    path('joure_edit/<int:pk>/',views.joure_edit , name='joure_edit'),
    path('joure_delete/<int:pk>/',views.joure_delete , name='joure_delete'),

    path('niveau_ajout/',views.niveau_ajout , name='niveau_ajout'),
    path('niveau_edit/<int:pk>/',views.niveau_edit , name='niveau_edit'),
    path('niveau_delete/<int:pk>/',views.niveau_delete , name='niveau_delete'),

    path('cours_ajout/<int:pk>/',views.cours_ajout , name='cours_ajout'),
    path('cours_edit/<int:pk>/',views.cours_edit , name='cours_edit'),
    path('cours_delete/<int:pk>/',views.cours_delete , name='cours_delete'),

    path('groupe_ajout/<int:pk>/',views.groupe_ajout , name='groupe_ajout'),
    path('groupe_edit/<int:pk>/',views.groupe_edit , name='groupe_edit'),
    path('groupe_delete/<int:pk>/',views.groupe_delete , name='groupe_delete'),

    path('detail_c_ajout/<int:pk>/',views.detail_c_ajout , name='detail_c_ajout'),
    path('detail_c_edit/<int:pk>/',views.detail_c_edit , name='detail_c_edit'),
    path('detail_c_delete/<int:pk>/',views.detail_c_delete , name='detail_c_delete'),

    path('prof_indispo_ajout/<int:pk>/',views.prof_indispo_ajout , name='prof_indispo_ajout'),
    path('prof_indispo_edit/<int:pk>/',views.prof_indispo_edit , name='prof_indispo_edit'),
    path('prof_indispo_delete/<int:pk>/',views.prof_indispo_delete , name='prof_indispo_delete'),

    path('prof_preferance_ajout/<int:pk>/',views.prof_preferance_ajout , name='prof_preferance_ajout'),
    path('prof_preferance_edit/<int:pk>/',views.prof_preferance_edit , name='prof_preferance_edit'),
    path('prof_preferance_delete/<int:pk>/',views.prof_preferance_delete , name='prof_preferance_delete'),

    path('groupe_indispo_ajout/<int:pk>/',views.groupe_indispo_ajout , name='groupe_indispo_ajout'),
    path('groupe_indispo_edit/<int:pk>/',views.groupe_indispo_edit , name='groupe_indispo_edit'),
    path('groupe_indispo_delete/<int:pk>/',views.groupe_indispo_delete , name='groupe_indispo_delete'),

    path('cal_exception_ajout/<int:pk>/',views.cal_exception_ajout , name='cal_exception_ajout'),
    path('cal_exception_edit/<int:pk>/',views.cal_exception_edit , name='cal_exception_edit'),
    path('cal_exception_delete/<int:pk>/',views.cal_exception_delete , name='cal_exception_delete'),

    path('chevauch_ajout/<int:pk>/',views.chevauch_ajout , name='chevauch_ajout'),
    path('chevauch_edit/<int:pk>/',views.chevauch_edit , name='chevauch_edit'),
    path('chevauch_delete/<int:pk>/',views.chevauch_delete , name='chevauch_delete'),



    # ##############end add object  ###############

    path('dep_matiers/<int:pk>/',views.dep_matiers , name='dep_matiers'),
    path('filier_classes/<int:pk>/',views.filier_classes , name='filier_classes'),
    path('classe_groupe/<int:pk>/',views.classe_groupe , name='classe_groupe'),
    path('classe_matiere/<int:pk>/',views.classe_matiere , name='classe_matiere'),

    path('groupe_cours/<int:pk>/',views.groupe_cours , name='groupe_cours'),
    path('groupe_indispo/<int:pk>/',views.groupe_indispo , name='groupe_indispo'),
    path('groupe_indispo_creneau/<int:pk>/',views.groupe_indispo_creneau , name='groupe_indispo_creneau'),
    path('groupe_indispo_jours/<int:pk>/',views.groupe_indispo_jours , name='groupe_indispo_jours'),
    path('prof_cours/<int:pk>/',views.prof_cours , name='prof_cours'),
    path('prof_indispo/<int:pk>/',views.prof_indispo , name='prof_indispo'),
    path('prof_indispo_creneau/<int:pk>/',views.prof_indispo_creneau , name='prof_indispo_creneau'),
    path('prof_indispo_jours/<int:pk>/',views.prof_indispo_jours , name='prof_indispo_jours'),
    path('prof_preferance/<int:pk>/',views.prof_preferance , name='prof_preferance'),
    path('detail_c/<int:pk>/',views.detail_c , name='detail_c'),
    path('filiere/<int:pk>/',views.filiere , name='filiere'),
    path('prof/<int:pk>/',views.prof , name='prof'),
    path('j_creneaux/<int:pk>/',views.j_creneaux , name='j_creneaux'),
    path('c_exception/<int:pk>/',views.c_exception , name='c_exception'),


    path('emploi/<int:pk>/',views.emploi , name='emploi'),


]

user/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView, LogoutView
from django.conf.urls.static import static
from django.conf import settings
app_name='user'

urlpatterns = [

    # path('login/', LoginView.as_view(template_name='user/login.html'), name='login'),
    path('', views.login_user, name=''),
    # path('logout/', LogoutView.as_view(template_name='user/logout.html'), name='logout'),
    path('logout/', views.logout_user, name='logout')
    ,]

templates/base.html
{% load static %}

<!doctype html>
<html class="no-js" lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Composant</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- favicon

		============================================ -->
<!-- Font Awesome -->
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

    <!-- Moment.js -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.23.0/moment.min.js" integrity="sha256-VBLiveTKyUZMEzJd6z2mhfxIqz3ZATCuVMawPZGzIfA=" crossorigin="anonymous"></script>

    <!-- Tempus Dominus Bootstrap 4 -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.1.2/css/tempusdominus-bootstrap-4.min.css" integrity="sha256-XPTBwC3SBoWHSmKasAk01c08M6sIA5gF5+sRxqak2Qs=" crossorigin="anonymous" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.1.2/js/tempusdominus-bootstrap-4.min.js" integrity="sha256-z0oKYg6xiLq3yJGsp/LsY9XykbweQlHl42jHv2XTBz4=" crossorigin="anonymous"></script>

    <link rel="shortcut icon" type="image/x-icon" href="{% static 'static_file/img/favicon.ico ' %}">
    <!-- Google Fonts
		============================================ -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,700,900" rel="stylesheet">
    <!-- Bootstrap CSS
		============================================ -->
    <link rel="stylesheet" href="{% static 'static_file/css/bootstrap.min.css' %}">
    <!-- Bootstrap CSS
		============================================ -->
    <link rel="stylesheet" href="{% static 'static_file/css/font-awesome.min.css' %}">
    <!-- owl.carousel CSS
		============================================ -->
    <link rel="stylesheet" href="{% static 'static_file/css/owl.carousel.css' %}">
    <link rel="stylesheet" href="{% static 'static_file/css/owl.theme.css' %}">
    <link rel="stylesheet" href="{% static 'static_file/css/owl.transitions.css' %}">

    <!--<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
-->

    <!-- animate CSS
		============================================ -->
    <link rel="stylesheet" href="{% static 'static_file/css/animate.css ' %}">
    <!-- normalize CSS
		============================================ -->
    <link rel="stylesheet" href="{% static 'static_file/css/normalize.css ' %}">
    <!-- meanmenu icon CSS
		============================================ -->
    <link rel="stylesheet" href="{% static 'static_file/css/meanmenu.min.css ' %}">
    <!-- main CSS
		============================================ -->
    <link rel="stylesheet" href="{% static 'static_file/css/main.css' %}">
    <!-- educate icon CSS
		============================================ -->
    <link rel="stylesheet" href="{% static 'static_file/css/educate-custon-icon.css' %}">
    <!-- morrisjs CSS
		============================================ -->
    <link rel="stylesheet" href="{% static 'static_file/css/morrisjs/morris.css' %}">
    <!-- mCustomScrollbar CSS
		============================================ -->
    <link rel="stylesheet" href="{% static 'static_file/css/scrollbar/jquery.mCustomScrollbar.min.css' %}">
    <!-- metisMenu CSS
		============================================ -->
    <link rel="stylesheet" href="{% static 'static_file/css/metisMenu/metisMenu.min.css' %}">
    <link rel="stylesheet" href="{% static 'static_file/css/metisMenu/metisMenu-vertical.css' %}">
    <!-- calendar CSS
		============================================ -->
    <link rel="stylesheet" href="{% static 'static_file/css/calendar/fullcalendar.min.css' %}">
    <link rel="stylesheet" href="{% static 'static_file/css/calendar/fullcalendar.print.min.css' %}">
    <!-- style CSS
		============================================ -->
    <link rel="stylesheet" href="{% static 'static_file/style.css' %}">
    <!-- responsive CSS
		============================================ -->
    <link rel="stylesheet" href="{% static 'static_file/css/responsive.css' %}">
    <link rel="stylesheet" href="{% static 'static_file/css/fontawesome-all.min.css' %}">
    <!-- modernizr JS
		============================================ -->
    <script src="{% static 'static_file/js/vendor/modernizr-2.8.3.min.js' %}"></script>
</head>


<body>


    <!-- Start Left menu area -->
    <div class="left-sidebar-pro">
        <nav id="sidebar" class="">
            <div class="sidebar-header">
                <a href="#"><img class="main-logo"  src="{% static 'static_file/img/logo/logo1.png ' %}" style="width:130px;heigth:40px"alt="" /></a>
                <strong><a href="#"><img src="{% static 'static_file/img/logo/logosn.png ' %}" alt="" /></a></strong>
            </div>



            <div class="left-custom-menu-adp-wrap comment-scrollbar">
                <nav class="sidebar-nav left-sidebar-menu-pro">
                    <ul class="metismenu" id="menu1">
                        <li>
                            <a class="has-arrow" href="all-professors.html" aria-expanded="false"><i class="fa fa-home"></i><span class="mini-click-non">  Emploi</span></a>
                            <ul class="submenu-angle" aria-expanded="false">
                            <li>
                            <a title="Liste de Departement" href="{% url 'iscae_emploi:dp' %}"><i class="fa fa-building"></i><span class="mini-sub-pro">  Départements</span></a>
                        </li>



                        <li>
                            <a title="touts les salle" href="{% url 'iscae_emploi:salle' %}"><i class="fa fa-house-user"></i><span class="mini-sub-pro">  Salles</span></a>
                        </li>


                        <li>
                            <a title="les niveaux" href="{% url 'iscae_emploi:niveau' %}"><i class="fa fa-layer-group"></i><span class="mini-sub-pro">  Niveaux</span></a>
                        </li>

                        <li>
                            <a title="les jours ouvrable" href="{% url 'iscae_emploi:jours' %}"><i class="fab fa-dashcube"></i><span class="mini-sub-pro">  Jours</span></a></li>


                        <li>
                            <a title="les Créneau disponible" href="{% url 'iscae_emploi:creneaux' %}"><i class="fa fa-hourglass-half"></i><span class="mini-sub-pro">  Créneaux</span></a>
                        </li>



                        <li>
                            <a title="les calandriers" href="{% url 'iscae_emploi:calandriers' %}"><i class="fa fa-calendar-alt"></i><span class="mini-sub-pro">  Calandriers</span></a>
                        </li>


                        <li>
                            <a title="touts les cours" href="{% url 'iscae_emploi:cours' %}"><i class="fa fa-chalkboard-teacher"></i><span class="mini-sub-pro">  Cours</span></a>
                        </li>
                        


                            </ul>
                        </li>




                    </ul>
                </nav>
            </div>
        </nav>
    </div>
    <!-- End Left menu area -->
    <!-- Start Welcome area -->
    <div class="all-content-wrapper">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="logo-pro">
                        <a href="index.html"><img class="main-logo" src="{% static 'static_file/img/logo/logo1.png ' %}" style="width:130px;heigth:40px" alt="" /></a>
                    </div>
                </div>
            </div>
        </div>
        <div class="header-advance-area">
            <div class="header-top-area">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                            <div class="header-top-wraper">
                                <div class="row">
                                    <div class="col-lg-1 col-md-0 col-sm-1 col-xs-12">
                                        <div class="menu-switcher-pro">
                                            <button type="button" id="sidebarCollapse" class="btn bar-button-pro header-drl-controller-btn btn-info navbar-btn">
													<i class="fa fa-align-justify" aria-hidden="true"></i>
												</button>
                                        </div>
                                    </div>
                                     <div class="col-lg-5 col-md-5 col-sm-12 col-xs-12">
                                        <div class="header-right-info">
                                            <ul class="nav navbar-nav mai-top-nav header-right-menu">

                                                <li class="nav-item">
                                                    <a href="#" data-toggle="dropdown" role="button" aria-expanded="false" class="nav-link dropdown-toggle">

															<span class="admin-name">Bonjour {{ user.get_username }}</span>
															<i class="fa fa-angle-down edu-icon edu-down-arrow"></i>
														</a>
                                                    <ul role="menu" class="dropdown-header-top author-log dropdown-menu animated zoomIn">
                                                        <li><a href="{% url 'admin:auth_user_change' user.id %}"><span class="edu-icon edu-home-admin author-log-ic"></span>Mon Compte</a>
                                                        </li>

                                                        <li><a href="{% url 'user:logout'  %}"><span class="edu-icon edu-locked author-log-ic"></span>Se déconnecter</a>
                                                        </li>
                                                    </ul>
                                                </li>

                                            </ul>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>




    </div>

    <!-- jquery
		============================================ -->
    <script src="{% static 'static_file/js/vendor/jquery-1.12.4.min.js' %}"></script>
    <!-- bootstrap JS
		============================================ -->
    <script src="{% static 'static_file/js/bootstrap.min.js' %}"></script>
    <!-- wow JS
		============================================ -->
    <script src="{% static 'static_file/js/wow.min.js' %}"></script>
    <!-- price-slider JS
		============================================ -->
    <script src="{% static 'static_file/js/jquery-price-slider.js' %}"></script>
    <!-- meanmenu JS
		============================================ -->
    <script src="{% static 'static_file/js/jquery.meanmenu.js' %}"></script>
    <!-- owl.carousel JS
		============================================ -->
    <script src="{% static 'static_file/js/owl.carousel.min.js' %}"></script>
    <!-- sticky JS
		============================================ -->
    <script src="{% static 'static_file/js/jquery.sticky.js' %}"></script>
    <script src="{% static 'static_file/js/fontawesome-all.min.js' %}"></script>
    <!-- scrollUp JS
		============================================ -->
    <script src="{% static 'static_file/js/jquery.scrollUp.min.js' %}"></script>
    <!-- counterup JS
		============================================ -->
    <script src="{% static 'static_file/js/counterup/jquery.counterup.min.js' %}"></script>
    <script src="{% static 'static_file/js/counterup/waypoints.min.js' %}"></script>
    <script src="{% static 'static_file/js/counterup/counterup-active.js' %}"></script>
    <!-- mCustomScrollbar JS
		============================================ -->
    <script src="{% static 'static_file/js/scrollbar/jquery.mCustomScrollbar.concat.min.js' %}"></script>
    <script src="{% static 'static_file/js/scrollbar/mCustomScrollbar-active.js' %}"></script>
    <!-- metisMenu JS
		============================================ -->
    <script src="{% static 'static_file/js/metisMenu/metisMenu.min.js' %}"></script>
    <script src="{% static 'static_file/js/metisMenu/metisMenu-active.js' %}"></script>
    <!-- morrisjs JS
		============================================ -->
    <script src="{% static 'static_file/js/morrisjs/raphael-min.js' %}"></script>
    <script src="{% static 'static_file/js/morrisjs/morris.js' %}"></script>
    <script src="{% static 'static_file/js/morrisjs/morris-active.js' %}"></script>
    <!-- morrisjs JS
		============================================ -->
    <script src="{% static 'static_file/js/sparkline/jquery.sparkline.min.js' %}"></script>
    <script src="{% static 'static_file/js/sparkline/jquery.charts-sparkline.js' %}"></script>
    <script src="{% static 'static_file/js/sparkline/sparkline-active.js' %}"></script>
    <!-- calendar JS
		============================================ -->
    <script src="{% static 'static_file/js/calendar/moment.min.js' %}"></script>
    <script src="{% static 'static_file/js/calendar/fullcalendar.min.js' %}"></script>
    <script src="{% static 'static_file/js/calendar/fullcalendar-active.js' %}"></script>
    <!-- plugins JS
		============================================ -->
    <script src="{% static 'static_file/js/plugins.js' %}"></script>
    <!-- main JS
		============================================ -->
    <script src="{% static 'static_file/js/main.js' %}"></script>

</body>
{% block body %}

{% endblock body %}

</html>